import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "./components/footer";
import { Figtree } from "next/font/google";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { cn } from "@/lib/utils";
import { ourFileRouter } from "./api/uploadthing/core";
import { Toaster } from "@/components/ui/toast";
import { CartProvider } from "@/components/cart/cart-provider";
import { CartDrawer } from "@/components/cart/cart-drawer";
import { getOrCreateCart, toCartSummary } from "@/lib/cart";

const figtree = Figtree({subsets:['latin'],variable:'--font-sans'});

const neueMontreal = localFont({
  src: "./fonts/ClashDisplay-Variable.woff2",
    
});

export const metadata: Metadata = {
  title: "ElgeeCosmetics",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const cart = await getOrCreateCart();
  const cartSummary = toCartSummary(cart);


  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", neueMontreal.className, "font-sans", figtree.variable)}
    >
      <body className="min-h-full flex flex-col">
        <NextSSRPlugin
          /**
           * The `extractRouterConfig` will extract **only** the route configs
           * from the router to prevent additional information from being
           * leaked to the client. The data passed to the client is the same
           * as if you were to fetch `/api/uploadthing` directly.
           */
          routerConfig={extractRouterConfig(ourFileRouter)}
        />
         <CartProvider initialCart={cartSummary}>
        {children}
         <CartDrawer />
                <Toaster />
        <Footer />
        </CartProvider>
      </body>
      
    </html>
  );
}
